theme: jekyll-theme-cayman
title: App Support
description: Support Page for My Apps
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
